.travis.yml, qemu/qemu_test.go
This commit adds a .travis file which enables Travis builds for
govmm.  The script builds the source and runs the unit tests
and gometalinter enabling
- misspell
- vet
- ineffassign
- gofmt
- gocyclo 15
- golint
- errcheck
- deadcode
=> Enable Travis builds

qemu/qemu.go, qemu/qemu_test.go
maxcpus is used to specify how many cpus a VM can have.
This attribute must be specified to enable the hotplugging CPUs capability,
otherwise the maximum number of CPU will be defined by the number of CPU
in -smp.
=> qemu: Add maxcpus attribute to -smp

qemu/qemu.go, qemu/qemu_test.go
A couple of patches for fixing up comments/naming as well as addition of basic vhost-user block device support.
To do still:
-exercise in complete stack (through pulling changes into CC-runtime)
-Add multiqueue support
-Add parameterization for block device fields.
=> Vhost-user:  add block device support

qemu/qemu.go, qemu/qemu_test.go
VSOCK sockets are added through a vhost PCI device.
It takes a device ID and a context ID, the latter being
the endpoint value to be reached from the host.
Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>
=> qemu: Add VSOCK support

qemu/qemu.go, qemu/qemu_test.go
SCSI controller allows scsi disks to be attached on the SCSI
bus created by the controller.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> scsi: Add a scsi controller device

.travis.yml, README.md
This commit enables unit test coverage computation in Travis CI builds.
Going forward, builds that decrease the unit test coverage by more than
1.0% will fail.
=> Compute coverage statistics for unit tests in Travis builds

qemu/qemu.go, qemu/qemu_test.go
certain machines types need to have extra options to enable or disable features
For example the machine type virt in certain hosts must have the gic version
(gic-version=3 or gic-version=host) to start without problems
=> qemu: add extra options for the machine type

qemu/qemu.go, qemu/qemu_test.go
DisableModern prevents qemu from relying on fast MMIO.
=> qemu: add DisableModern to SCSIController

qemu/qemu.go, qemu/qemu_test.go
IOThreads allow IO to be handled on a separate thread rather than the main event loop. This has a positive impact on performance in terms of throughput and latency.
=> Add ability to associate a SCSI controller device with an iothread

qemu/qemu.go, qemu/qemu_test.go, qemu/qmp.go, qemu/qmp_test.go
The PR adds necessary qemu config and APIs that help to enable the vm templating feature:
- a memory device path
- a boolean that controls if file backed memory is enabled
- a boolean that controls if file backed memory is shared
- Incoming structure that allows to set migration exec command line
- QMP migrate-set-capabilities that sets migration bypass-shared-memory capability
- QMP migrate that sets migration arguments
- QMP hotplug memory
related: kata-containers/runtime/pull/303
VM templating leverages qemu live migration and qemu's ability to use shared memory backend on the same host. The following graph shows the process of creating a template VM and creating new VMs based on it.
=> Add APIs to enable vm templating

qemu/qemu.go, qemu/qmp.go, qemu/qmp_test.go
Implement function to hotplug vsocks,	vsocks are needed
to communicate processes are running inside the VM
with processes are running on the host.
=> qemu/qmp: implement function to hotplug vsock-pci

qemu/qemu.go, qemu/qemu_test.go
`vhostfd` is the vhost file descriptor that holds the socket context ID
`disable-modern` prevents qemu from relying on fast MMIO
=> qemu: add vhostfd and disable-modern to vhost-vsock-pci

qemu/qmp.go, qemu/qmp_test.go
Implement function to hotplug and delete a network device to QEMU
=> qemu/qmp: implement function for hotplug network

qemu/qmp.go, qemu/qmp_test.go
`vhostfd` is used to specify the vhost-vsock device fd, and it holds
the context ID previously opened.
`disable-modern` is to disable the use of "modern" devices, it's used
to make azure VMs happy.
=> qemu: add vhostfd and disable-modern to vsock hotplug

qemu/qmp.go, qemu/qmp_test.go
Implement function to hotplug virtio serial ports, the serial ports
are visible in the guest at the directory /dev/virtio-ports.
implement function to hotplug character devices using as backend
unix sockets, binding a character device with a serial port allows
the communnication between processes running in the guest with
processes running in the host.
=> qemu/qmp: implement functions to hotplug chardevs and serial ports

qemu/qmp.go, qemu/qmp_test.go
Implement function to hotplug a network device to QEMU by fds.
Macvtap can only be hotplug by this way.
Fixes #26
=> qemu/qmp: add function for hotplug network by fds

qemu/qmp.go, qemu/qmp_test.go
For machines types based on PCIe like q35, device addr and bus must be specified.
For machines types based on PCI like pc, device addr must be specified and bus
is optional since devices can be hot plugged directly on the root bus.
=> qemu/qmp: add addr and bus to hotplug vsock devices

qemu/qemu.go
If no RTC is specified in the config then do not generate any RTC command line
options. RTC command line options are optional for QEMU so make Valid() return
false when presented with the empty version of the RTC struct containing empty
strings.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
=> qemu: Do not try and generate invalid RTC parameters

qemu/qmp.go, qemu/qmp_test.go
In addition to normal VFIO device, this patch adds VFIO mediated device
as a supplement to do hot plug on PCI(E) bridges.
Signed-off-by: Zhao Xinda <xinda.zhao@intel.com>
=> qemu/qmp: add vfio mediated device support

qemu/qmp.go, qemu/qmp_test.go
With qemu 2.10, a write lock was added for qcow images that
prevents the same image to be passed more than once.
This can be over-ridden using the --share-rw option which is
desired for raw images.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
=> disk: Add --share-rw option for hotplugging disks

qemu/qemu.go
This will kill the process when the context is cancelled. As using a nil
context is not permitted it is necessary to substitute with a real
context if it is not initialised in the Config struct.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
=> qemu: Use the supplied context.Context for launching

qemu/qmp.go
Before calling any other command it is necessary to call
ExecuteQMPCapabilities() otherwise QEMU will not process the subsequent QMP
commands.
Signed-off-by: Rob Bradford <robert.bradford@intel.com>
=> qmp: Remind users that you must first call ExecuteQMPCapabilities()

qemu/qmp.go, qemu/qmp_test.go
If we hotplug a nic with args mq=on, its qdisc will be mq by default.
This aligns with cold plug nics.
=> qemu/qmp: support hotplug a nic whose qdisc is mq

qemu/qmp.go
govmm has ExecuteBlockdevAdd() function and ExecuteBlockdevDel() function
doesn't compatible with qemu 2.8,because blockdev-add and x-blockdev-del usages
are different between qemu 2.7 and qemu 2.8
Follow the qemu 2.7 and qemu 2.8 qmp-commands.txt documents to modify ExecuteBlockdevAdd()
function and ExecuteBlockdevDel() function to be compatible with qemu 2.8
Signed-off-by: flyflypeng <jiangpengfei9@huawei.com>
=> govmm: modify govmm to be compatible with qemu 2.8

qemu/qmp.go, qemu/qmp_test.go
If host doesn't support vhost_net, we won't pass vhost="on" in QMP.
=> qemu/qmp: nic can works without vhost

qemu/image.go
The contents of .iso used to bootstrap VMs with cloudinit are
initialised using a precreated, short-lived  directory.  The
permissions on this directory were too lenient.  This commit
restricts access to this directory to the user and his/her group.
=> qemu/image: Reduce permissions of .iso creation dir

qemu/qmp.go
In addition to normal VFIO device, this patch adds VFIO mediated device
as a supplement to do hot plug on root bus
Signed-off-by: Zhao Xinda <xinda.zhao@intel.com>
=> qemu/qmp: add vfio mediated device support on root bus

qemu/qemu.go, qemu/qemu_test.go
The memory-backend-ram should also be set to a numa node instead of
being inserted as a new device. Otherwise it becomes additional memory
and requires explicit online to be available, instead of just being a
backend of the memory specified by -m option.
=> qemu: skip setting system memory if it is set via dimm device

qemu/qemu.go, qemu/qemu_test.go
In case the type of bridge is PCIEBridge, which we expect as ending
up using pcie-pci-bridge device from Qemu, the properties chassis_nr
and shpc don't exist.
This commit simply fixes this use case by removing those parameters
from the command line.
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> qemu: Fix the support of PCIe bridge

qemu/qemu.go
Rather than show the generic "qemu", log the full path to the
particular qemu binary being used.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> qemu: Show full path to qemu binary at launch time

qemu/qemu.go, qemu/qemu_test.go, qemu/qmp.go, qemu/qmp_test.go
Add support for virtio-balloon.
- Add test
- Support disable-modern
- Support deflate-on-oom
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
=> qemu: Add virtio-balloon device suppport.

qemu/qmp.go
This patch fixes the wrong behavior of specifying a netdev, MAC
address or PCI address entry when those were empty. Instead, it
does not provide those entries if the content is empty.
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> qemu: Fix virtio-net-pci QMP command

qemu/qemu.go, qemu/qemu_test.go
Add input for `-pidfile` option of qemu, so that we can get pid of
qemu main process, and apply resource limitations to it.
Fixes #62
Signed-off-by: l00397676 <lujingxiao@huawei.com>
=> qemu: add support for pidfile option

qemu/qmp.go, qemu/qmp_test.go
ExecuteBlockdevAddWithCache has two more parameters direct and noFlush
than ExecuteBlockdevAdd.
They are cache-related options for block devices that are described in
https://github.com/qemu/qemu/blob/master/qapi/block-core.json.
direct denotes whether use of O_DIRECT (bypass the host page cache)
is enabled.  noFlush denotes whether flush requests for the device are
ignored.
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> qemu/qmp: add new function ExecuteBlockdevAddWithCache

qemu/qemu.go, qemu/qemu_test.go
The PR changes the Context ID type from `uint32` to `uint64` and checks the maximum value that the id can have
=> qemu: change Context ID for Vsock to uint64

qemu/qmp.go
> "{\"error\": {\"class\": \"GenericError\", \"desc\": \"Parameter 'mem-path' is unexpected\"}}"
I got the error message when worked around hotplug memory to QEMU using host hugetlbfs.
So i checked the QMP command `object-add` code in QEMU, and found `"mem-path"` should be the key of map `"props"` instead of `"args"`.
The `object-add` be added since 2.0, and the newest 2.12 has the same definition.
https://github.com/qemu/qemu/blob/stable-2.0/qapi-schema.json#L2958
https://github.com/qemu/qemu/blob/stable-2.12/qapi/misc.json#L1846
=> qmp: fix mem-path properties for hotplug memory.

CONTRIBUTORS.md, qemu/qemu.go, qemu/qemu_s390x.go, qemu/qemu_s390x_test.go, qemu/qmp.go, qemu/qmp_test.go
The PR adds the s390x support. It sets the CCW devices and sets to false all the devices in the mapping isVirtioPCI. It reimplements the functions
QemuNetdevParam and QemuDeviceParam to print an error message if the vhost-user devices are used. It introduces a new function ExecuteNetCCWDeviceAdd for qmp for the CCW devices.
Fixes: #37
Co-authored-by: Yash D Jain <ydjainopensource@gmail.com>
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
=> qemu: Add s390x support

qemu/qmp.go, qemu/qmp_test.go
For devices that actually support the option disable-modern, this
current commit provides a proper flag to the caller. This will allow
for better support when used in nested environment as virtio-pci
devices should rely on virtio 0.9 instead of 1.0 due to a bug in
KVM.
Fixes #80
Signed-off-by: Sebastien Boeuf <sebastien.boeuf@intel.com>
=> qemu: Allow disable-modern option from QMP

CONTRIBUTORS.md, qemu/qmp.go, qemu/qmp_test.go
ExecuteNVDIMMDeviceAdd can add a nvdimm disk to qemu.
Not implement NVDIMM device delete function because qemu doesn't support it.
Signed-off-by: Hui Zhu <teawater@hyper.sh>
=> qmp: Add nvdimm support

.travis.yml, qemu/image.go, qemu/qemu.go, qemu/qemu_test.go, qemu/qmp.go
The travis builds were failing due to changes to gometalinter.  This PR fixes the issue by modifying the parts of the code that gometalinter was complaining about and updating the versions of Go used to build govmm in the CI builds.
=> Fix travis

qemu/qmp.go
In order to hotplug vCPU on ppc64le, we need not
pass threadID and socketID. So conditionally pass
arguments when executing CPU device add.
Fixes: #83
Signed-off-by: Nitesh Konkar niteshkonkar@in.ibm.com
=>  qmp: Conditionally pass threadID and socketID when CPU device add 

qemu/qemu.go
The QEMU vhost-user-fs-pci device provides virtio-fs host<->guest file
system sharing (https://virtio-fs.gitlab.io/).  The device is
instantiated like this:
$ qemu -chardev socket,path=/tmp/vhost-fs.sock,id=chr0
-device vhost-user-fs-pci,tag=myfs,chardev=chr0,cache-size=4G,versiontable=/dev/shm/fuse_shared_versions
This patch adds the VhostUserFS DeviceDriver and command-line generation
for this QEMU device.
Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>
Note that vhost-user-fs-pci is not yet available in qemu.git/master so it may be desirable to leave this pull request as "work in progress" until upstream QEMU merges the feature.  This govmm patch is a prerequisite for Kata Containers virtio-fs support.
=> govmm: add VhostUserFS vhost-user device type

qemu/qmp.go
Since []byte channel type transfer slice info(include slice underlying array pointer, len, cap)
between channel sender and receiver. scanner.Bytes() function returned slice's underlying array
may point to data that will be overwritten by a subsequent call to Scan(reference from:
https://golang.org/pkg/bufio/#Scanner.Bytes), which may make consecutive scan() call write the
read data into the same underlying array which causes receiver read mixed data,so we need to
copy line to new allocated space and then send to channel receiver to solve this problem.
Fixes: #88
Signed-off-by: jiangpengfei <jiangpengfei9@huawei.com>
=> qemu/qmp: fix readLoop() reuse scanner.Bytes() underlying array problem

qemu/qemu.go
QEMU supports finer-grained units than GiB.  Change the cache size to
MiB so users have more control over the cache size.
Note that changing the semantics of the CacheSize field is fine because
there are no users of this API yet.  kata-runtime will be the first
users and prefers MiB instead of GiB.
Signed-off-by: Stefan Hajnoczi <stefanha@redhat.com>
=> qemu: use MiB instead of Gib for virtio-fs cache size

qemu/qemu.go, qemu/qemu_arch_base.go
The driver for VirtioBlock should "virtio-blk-pci" instead
of "virtio-blk".
Fixes:#92
Signed-off-by: lifupan <lifupan@gmail.com>
=> qemu: fix the issue of wrong driver for VirtioBlock

qemu/qemu.go, qemu/qemu_test.go, qemu/qmp.go, qemu/qmp_test.go
qemu commandline supports -incoming defer
and qmp supports migrate-incoming uri.
=> qemu: add migration incoming defer support

qemu/qmp.go, qemu/qmp_test.go
Hotplugged memory could be backed by a file on the host with sharing
turned on. This change allows qmp to pass that option to a govmm.
Signed-off-by: Ganesh Maharaj Mahalingam <ganesh.mahalingam@intel.com>
=> Allow sharing of memory backend file

qemu/qemu.go, qemu/qemu_arch_base.go, qemu/qemu_arch_base_test.go, qemu/qemu_test.go, qemu/qemus390x.go, qemu/qemus390x_test.go, qemu/qmp.go, qemu/qmp_test.go
The PR adds the devno parameters and the virtio-blk-ccw support. 
Fixes: #98
=> Support for virtio-blk-ccw

qemu/qemu.go, qemu/qemu_arch_base_test.go, qemu/qemu_test.go
Close #97 
As the issue says, in our environment, sometimes need to specified vendor-id and device-id.
=> Support x-pci-vendor-id and x-pci-device-id pass to qemu

qemu/qmp.go, qemu/qmp_test.go
In QEMU 4.1 the CPU topology for x86 will change to:
`socket > die > core > thread`.
Add `die-id` field to `CPUProperties` and include it in CPU hotplugging
=> qemu: support x86 SMP die

qemu/qmp.go, qemu/qmp_test.go
Support for function isSocketIDSupported, isThreadIDSupported and isDieIDSupported.
The functions check if the cpu driver and the qemu version support the
id parameter.
Fixes: #102
The support table for various param looks like:
| Arch | cpu driver             | socket id | thread id | die id | cpu hotplug |
| ---     |  ---                         |      ---        |   ---         |  --       | ---- |
| x86_64 |    host-x86_64-cpu | y               |   y           | y   ( >= Qemu 4.1)     | y |
| s390x |        host-s390x-cpu | n | n |n | y | 
| arm64  |        host-arm-cpu                   |    y             |   y           |    n        | n |
| ppc64le |     host-powerpc64-cpu     |    n             | n             |     n      |    y |
taken from …
=> qmp: add checks for the CPU toplogy

qemu/qmp.go, qemu/qmp_test.go
The upper hyervisor manager application maybe need to wait some
QMP event to control boot sequence, but the event we wanted maybe
not exist in some older version, so we need query all QMP ABI and
check the event is supported or not.
related: kata-containers/runtime#1918
Signed-off-by: Ning Bo <ning.bo9@zte.com.cn>
=> qmp: support command 'query-qmp-schema'

qemu/qemu.go, qemu/qemu_test.go, qemu/qmp.go, qemu/qmp_test.go
1. add qemu logfile so that we can check why qemu fails
2. treat memory memory preallocation as a property for different memory backends
3. add query-status qmp API
=> improve qemu interaction

qemu/qemu.go
This allows multiple instances of qemu to share the same file for
virtio-blk device.
Fixes: #108
Signed-off-by: Jan Schintag <jan.schintag@de.ibm.com>
=> virtio-blk: Add support for share-rw flag

.travis.yml, qemu/qemu_arch_base.go, qemu/qemu_arch_base_test.go, qemu/qemu_s390x.go, qemu/qemu_s390x_test.go
Since we have travis support for s390x. Let's enable it
Signed-off-by: Alice Frosi <afrosi@de.ibm.com>
=> s390x: add s390x travis support

qemu/qmp.go, qemu/qmp_test.go
User can hotplug vhost-user device into QEMU instance via QMP.
The hotplug calling steps are:
1. ExecuteCharDevUnixSocketAdd();
2 ExecutePCIVhostUserDevAdd();
The hotremove calling steps are:
1. ExecuteDeviceDel()
2. ExecuteChardevDel()
=> qmp: add ExecutePCIVhostUserDevAdd and ExecuteChardevDel to hotplug vhost-user device

qemu/qmp.go, qemu/qmp_test.go
Add ExecMemdevAdd and ExecQomSet API to support virtio-mem.
Signed-off-by: Hui Zhu <teawater@antfin.com>
=> qmp: Add ExecMemdevAdd and ExecQomSet API

qemu/qemu.go, qemu/qemu_arch_base.go, qemu/qemu_arch_base_test.go, qemu/qmp.go, qemu/qmp_test.go
PCIe devices can be hot-plugged to PCIe Root Port:
- Support pcie-root-port device
- Add 'bus' property to vfio-pci device
- Add test
=> qemu: Add pcie-root-port device support.

qemu/qemu.go
As there's no guarantee that ".cache-size" is a supported QEMU property,
let's not add it to the QEMU command line when the user explicitly set
virtio_fs_cache_size to zero.
By not always setting ".cache-size" property we avoid errors like:
```
$ sudo podman --runtime=/usr/bin/kata-runtime run --security-opt label=disable -it fedora:31 /bin/bash
Error: failed to launch qemu: exit status 1, error messages from qemu log: qemu-kvm: -device vhost-user-fs-pci,chardev=char-88c350403e95d3db,tag=kataShared,cache-size=0M: Property '.cache-size' not found: OCI runtime error
```
Signed-off-by: Fabiano Fidêncio <fidencio@redhat.com>
=> qemu: Don't set ".cache-size=" when CacheSize is 0

qemu/qemu.go, qemu/qemu_arch_base_test.go, qemu/qemu_s390x_test.go, qemu/qemu_test.go
So that we can attach it readonly.
Signed-off-by: Peng Tao <bergwolf@hyper.sh>
=> qemu: add block device readonly support

qemu/qmp.go, qemu/qmp_test.go
According to QEMU's nvdimm documentation: When 'pmem' is 'on' and QEMU is
built with libpmem support, QEMU will take necessary operations to guarantee
the persistence of its own writes to the vNVDIMM backend.
=> qemu: add pmem flag to memory-backend-file

qemu/qemu.go, qemu/qemu_test.go
Following on from #111 which added support for multiple virtio transports,
add code to use virtio-mmio as the transport when booting a guest with
the microvm machine type and add a microvm case when checking for
NUMA support. Also add a test case for machine string parsing.
Signed-off-by: Liam Merwick <liam.merwick@oracle.com>
=> qemu: Add microvm machine type support

qemu/qemu.go
For rtc clock, there are types "host/rt/vm".
Signed-off-by: Shuicheng Lin <shuicheng.lin@intel.com>
=> Add rt clock definition for rtc clock in qemu

qemu/qemu.go, qemu/qemu_arch_base_test.go, qemu/qemu_test.go
Allow API consumers to change the maximum number of ports in the virtio-serial
devices, setting a lower number of ports can improve the boot time and
reduce the attack surface.
fixes #120
=> qemu: Add max_ports option to virtio-serial device

qemu/qemu.go, qemu/qemu_test.go
The following options can be provided:
Intremap: activates interrupt remapping
DeviceIotlb: enables device IOTLB support for the vIOMMU
CachingMode: enables Cahing Mode
See: https://wiki.qemu.org/Features/VT-d
Fixes: #126 
Signed-off-by: Adrian Moreno <amorenoz@redhat.com>
=> qemu: add IOMMU Device

qemu/qmp.go
vhost is a Netdev Tap Option used to configure a host TAP network interface
backend, according to the QMP API documentation the type for such option must
be a boolean. Use boolean type for vhost option to fix the following
error on recent versions of QEMU:
```
Invalid parameter type for 'vhost', expected: boolean
```
cc @amshinde 
=> qemu/qmp: use boolean type for the vhost

qemu/qemu.go, qemu/qemu_arch_base_test.go, qemu/qemu_s390x_test.go, qemu/qemu_test.go
multidevs specifies how to deal with multiple devices being shared with a 9p
export. `multidevs=remap` fixes the following warning:
```
9p: Multiple devices detected in same VirtFS export, which might lead to file
ID collisions and severe misbehaviours on guest!
You should either use a separate export for each device shared from host or
use virtfs option 'multidevs=remap'!
```
=> Add multidevs option to fsdev

qemu/qemu.go, qemu/qemu_test.go
The Kata architecture does not support rebooting VMs (the lifecycle
being start/exec/kill) and if a VM is killed (e.g. using sysrq-trigger),
the VM does not exit fully and other layers do not notice the state change.
Kata needs a way to tell QEMU to run with the '--no-reboot' option
so that the guest VM exits and does not attempt to reboot.
Add a NoReboot boolean Knob so when Knobs.NoReboot is set, the '--no-reboot'
command-line option will be passed to QEMU on startup.
Signed-off-by: Liam Merwick <liam.merwick@oracle.com>
=> qemu: Add NoReboot config Knob for qemuParams

qemu/qemu.go, qemu/qemu_s390x_test.go
Add knobs.IOMMUPlatform and iommu_platform=on options for ccw device for s390x, which is also OK to add same option for pci device in the future if need.
Signed-off-by: Qi Feng Huo <huoqif@cn.ibm.com>
=> qemu: add iommu_platform knob for qemuParams

.travis.yml
Fix the following error:
```
Bad response status from coveralls: 422
{"message":"service_job_id (717167073) must be unique for Travis Jobs
not supplying a Coveralls Repo Token","error":true}
The command "$GOPATH/bin/goveralls -v -service=travis-ci" exited with 1.
```
fixes #135
=> travis: Run coveralls after success

.github/workflows/main.yml, .travis.yml
Use github actions to run unit tests.
Github actions service looks more stable and reliable than travis.
fixes #136
=> github: enable github actions

qemu/qemu.go, qemu/qmp.go, qemu/qmp_test.go
This adds `ExecuteAPVFIOMediatedDeviceAdd` to `qemu/qmp.go`, which executes a hot-plug for an IBM Adjunct Processor (AP) VFIO device ([kernel doc here](https://www.kernel.org/doc/html/latest/s390/vfio-ap.html)).
See also Issue [#491](https://github.com/kata-containers/kata-containers/issues/491) in the Kata Containers project.
/cc @alicefr
Fixes: #133
If this LGTY in general, I'd create a Do-Not-Merge re-vendoring PR in Kata first to ensure compatibility.
=> Add support for hot-plugging IBM Adjunct Processor (AP) devices

qemu/qmp.go, qemu/qmp_test.go
Add a function to access the qom-get QMP command so we can query
information from qemu.
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
=> Add qom-get function

qemu/qemu.go, qemu/qemu_test.go
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
Append `fw_cfg` flag
=> qemu: add fw_cfg flag to config

.github/workflows/main.yml, .travis.yml, CONTRIBUTING.md, README.md, qemu/examples_test.go
`govmm` is now part of the `kata-containers` GitHub organisation, so
update to reflect this.
Fixes: #145.
Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>
=> misc: Update for new GitHub organisation name

qemu/qemu.go, qemu/qemu_test.go
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
This PR aims to correct the behavior of the `fw_cfg` flag under two aspects:
* Make fw_cfg a slice - in fact as reported by @jodh-intel fw_cfg can be used `>=0` so it is better represented as a slice/array rather than a single struct
* Treating fw_cfg fields with double quotes fails the lookup - I've tried and it did not work. in fact passing for instance the file `file="file.json"` this would look up the file named `"file.json"`.
=> Make fw_cfg a slice

qemu/qemu.go, qemu/qemu_arch_base_test.go, qemu/qemu_s390x_test.go
Signed-off-by: Salvatore Mazzarino <dev@mazzarino.cz>
I'm not sure if this change looks legit but I create my block device in this way:
```go
var RAW qemu.BlockDeviceFormat = "raw"
blk := qemu.BlockDevice{
Driver:    qemu.VirtioBlock,
ID:        "rootfs",
AIO:       qemu.Threads,
File:      "rootfs.img",
Format:    RAW,
Interface: qemu.NoInterface,
Transport: qemu.TransportPCI,
}
```
and the output parameters are:
```sh
-device virtio-blk-pci,disable-modern=false,drive=rootfs,scsi=off,config-wce=off,romfile=
-drive id=rootfs,file=rootfs.img,aio=threads,format=raw,if=none
```
In this way, my instance does not bootstrap but when I have `serial=rootfs` appended in `-device` then it works and it bootstrap successfully.
=> Add serial ID to blk device

qemu/qemu.go, qemu/qemu_test.go, qemu/qmp.go, qemu/qmp_test.go
With this two features user can:
- Get event for GUEST_PANICKED
- Dump guest memory if needed
Fixes: #152
=> qemu: add pvpanic and dump guest memory support

qemu/qemu.go, qemu/qemu_test.go
flash image can store some critical data like firmware, enable it here.
Fixes: #140
Signed-off-by: Edmond AK Dantes <edmond.dantes.ak47@outlook.com>
@jodh-intel @jongwu @devimc
=> qemu: enable "-pflash"

qemu/qemu.go
dimm is supported on arm64, so add is to check list.
Signed-off-by: Jianyong Wu <jianyong.wu@arm.com>
Fixes: #155
@devimc @jodh-intel
=> qemu: add arm64 to support list of dimm

qemu/qmp.go, qemu/qmp_test.go
We should allow users to specify of a block device should be hotplugged
as read-only.
Fixes: #157
Signed-off-by: Eric Ernst <eric_ernst@apple.com>
=> qmp: Add ro argument for block-device hotplug funcs

qemu/examples_test.go, qemu/qemu.go, qemu/qemu_test.go
Use `on` and `off` to enable or disable features,
`no` prefix is deprecated
=> qemu: support QEMU 6

qemu/qemu.go, qemu/qemu_test.go
Devices loaders can be used to load some firmwares.
cc @sameo
=> qemu: add support for device loaders

qemu/qemu.go, qemu/qemu_test.go
Some architectures and setups do not support DIMM/NUMA. However, they
can still use memory backends, provided a memory backend of the same ID
is specified under -machine. Enable this functionality in
appendMemoryKnobs.
Fixes: #160
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>
=> qemu: Append memory backend for non-DIMM setups

qemu/qemu.go, qemu/qemu_arch_base_test.go
Currently, if romfile field is empty, the commandline will
shows like below:
-device driver=virtio-net-pci,...,mq=on,vectors=4,romfile=
This does not make sense, just remove this field in commandline
Add unittest support.
Signed-off-by: Michael Qiu <qiudayu@huayun.com>
=> Fix qemu commandline issue with empty romfile

qemu/qmp.go
In Kata, we are getting a *lot* of logs at runtime from QMP, in particular `read from QMP: xxxx`
Ideally we'd set this to only be visible for trace, but I did not see this working when adding a
V(7) check around these prints. To avoid filling journal with info that isn't useful, let's drop.
Fixes: #165
Signed-off-by: Eric Ernst <eric.g.ernst@gmail.com>
=> qmp: remove chatty log

qemu/qemu.go
Add CCW (s390x) device numbers to VhostUserDevices, as is with other
device types.
Fixes: #170
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>
=> qemu: VhostUserDevice CCW device numbers

qemu/qemu.go
Secure Execution, also known as Protected Virtualization in QEMU, is a 
confidential computing technology for s390x (IBM Z). Allow the
respective object.
Fixes: #172
Depends-on: #167 because when adding an object, it enables adding device parameters only when actually using a device ([relevant lines here](https://github.com/kata-containers/govmm/pull/167/files#diff-60d10e04edc58668f13d9932884322892005f9b39db600185b0b08872c750579R333-R336)), which is also required for Secure Execution. Should be rebased accordingly, which would effectively reduce this PR by that commit.
/cc @sameo @jimcadden @fitzthum
=> qemu: Add support for Secure Execution

qemu/qemu.go
Adding the support for Protected Execution Facility(PEF)
which is the confidential computing technology on ppc64le.
Fixes: #174
Depends-on: #167
Signed-off-by: Amulyam24 <amulmek1@in.ibm.com>
cc @bpradipt @clnperez
=> qemu: Add support for PEF

qemu/qmp.go, qemu/qmp_test.go
Currently virtio-mem-pci devices can be hotplugged only on the root bus.
This doesn't work for PCIe machines like q35.
Extend the API to optionally support hotplugging on PCI bridges.
Fixes: #176
Signed-off-by: Marcel Apfelbaum <marcel@redhat.com>
=> qemu: Allow hot-plugging memory devices on PCI bridges

qemu/qemu.go
Always join by ",", do not put commas in the parameter slices. Always
use the variable name `deviceParams`.
Fixes: #180
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>
/cc @jodh-intel
=> qemu: Consistent parameter building

qemu/qemu.go, qemu/qemu_test.go
Append `readonly=on` to a `memory-backend-file` object and
`unarmed=on` to a `nvdimm` device when `ReadOnly` is set to `true`
=> qemu: support read-only nvdimm

qemu/qemu.go, qemu/qemu_test.go
Update the govmm code in order to support "sandbox" feature on qemu,
which can introduce another protect layer on the host,
to make the secure container more secure.
Fixes: #185
Signed-off-by: Liang Zhou <zhoul110@chinatelecom.cn>
=> add support for "sandbox" feature to qemu

qemu/qmp.go
ExecuteBlockdevAdd() and ExecuteBlockdevAddWithCache() both appear to be
intended to create block devices in the guest which backend onto a block
device in the host. That seems to be the way that Kata always uses it.
However blockdevAddBaseArgs(), used by both those functions always uses the
"file" driver, which is only intended for use with regular file backends.
Use of the "file" driver for host block devices was deprecated in qemu-3.0,
and has been removed entirely in qemu-6.0 (commit 8d17adf34f5).  We should
be using the "host_device" driver instead.
fixes #191
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
=> Use 'host_device' driver for blockdev backends

README.md, qemu/qmp.go, qemu/qmp_test.go
For both memory and NVDIMM adds, govmm needs to add memory-backend-file objects using the object-add qmp command.
Currently, govmm puts various properties for the new object in the props field of the args field to the basic QMP request. However use of props has been deprecated in qemu since 5.0 (commit 5f07c4d60d09) and is removed entirely in qemu 6.0 (commit 50243407457a).
Since relying on this new behaviour requires QEMU >= 5.0 anyway - and Kata requires that anyway - drop support for older QEMU versions.
=> Don't use deprecated 'props' argument to QMP 'object-add'

qemu/qemu.go
- Remove extra comma when device parameters are already joined with
commas
- Enable iommu_platform for vhost user devices
Fixes: #178
Signed-off-by: Jakob Naucke <jakob.naucke@ibm.com>
=> qemu: Fix iommu_platform for CCW

qemu/qemu.go, qemu/qemu_arch_base_test.go, qemu/qemu_test.go
This adds fields to BridgeDevice struct to allow qemu's io-reserve,
mem-reserve and pref64-reserve properties to be set for PCI bridges.  This
is needed for Kata's upcoming change to ACPI hotplug.
fixes #200
Signed-off-by: David Gibson <david@gibson.dropbear.id.au>
=> govmm/qemu: Let IO/memory reservations be specified for bridge devices

qemu/qemu.go, qemu/qmp.go, qemu/qmp_test.go
Add support for --no-shutdown knob
```Don't exit QEMU on guest shutdown, but instead only stop the emulation.```
ExecuteSystemPowerdown issues `system_powerdown` and waits for `SHUTDOWN`. The event emitted is `POWERDOWN` per spec.
Without this we get an error even though the VM has shutdown  gracefully.
Per QEMU spec:
```
POWERDOWN (Event)
Emitted when the virtual machine is powered down through the power
control system, such as via ACPI.
Since
0.12
Example
<- { "event": "POWERDOWN",
"timestamp": { "seconds": 1267040730, "microseconds": 682951 } }
SHUTDOWN (Event)
Emitted when the virtual machine has shut down, indicating that qemu is
about to exit.
Arguments
guest: boolean
If true, the shutdown was triggered by a guest request (such as a
guest-initiated ACPI shutdown request or other …
```
=> Add clean shutdown support

qemu/qemu.go, qemu/qemu_test.go
- Add support for legacy serial device
- Additionally add support for the file backend for chardev
Legacy serial plus char backend file will allow us to support
capture of early boot messages.
Signed-off-by: Manohar Castelino <mcastelino@apple.com>
=> qemu: Add support for legacy serial device

qemu/qmp_test.go
Fix running test on 32bit arch.
`GOARCH=386 go test -v ./...`
=> qemu: Fix 32 bit int overflow in test file

qemu/qmp.go
Now the `wait` is passed to qmp command, even at non-server mode. This
will cause qemu return this error:
'wait' option is incompatible with socket in client connect mode
Fixes: #205
Signed-off-by: bin liu <liubin0329@gmail.com>
=> qemu: only set wait parameter for server mode socket based char device

qemu/qemu.go, qemu/qemu_arch_base_test.go
since qemu 6.0, readonly flag for block devices must be enable or
disable with `on` or `off` respectively.
=> qemu: update readonly flag for block devices
