kata-containers/govmm

- README.md
This commit adds three badges to the README.md file
- Goreportcard
- Godoc
- Travis
> Add badges to the README.md file

- qemu/qmp.go
- qemu/qmp_test.go
device_add qmp command for scsi devices accepts additional parameters like
scsi-id and lun. Implement function to add scsi devices. Devices
with drivers "scsi-hd" and "scsi-cd" are accepted.
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>
> scsi: Add function to send device_add qmp command for a scsi device

- qemu/qemu.go
- qemu/qemu_test.go
Append initrd image to qemu arguments if configured.
> qemu: add initrd support

- qemu/qemu_test.go
- qemu/qmp_test.go
This PR adds some negative test cases to govmm.  These new test cases improve the test coverage to 80%.
> Add some negative test cases

- qemu/qmp.go
- qemu/qmp_test.go
Implement query qemu memory devices function and testcase.
Signed-off-by: Clare Chen <clare.chenhui@huawei.com>
> qemu/qmp: support query-memory-devices qmp command.

- qemu/qemu.go
- qemu/qemu_test.go
Add knob to append rng-vitio device.
Signed-off-by: Jose Carlos Venegas Munoz <jose.carlos.venegas.munoz@intel.com>
> qemu: Add rng device .

- qemu/qmp.go
- qemu/qmp_test.go
Add "query-cpus" to query CPU information from qemu
Signed-off-by: Wei Zhang <zhangwei555@huawei.com>
> qmp: add "query-cpus" support

- qemu/qmp.go
- qemu/qmp_test.go
It sends query-migrate qmp command to check migration status.
> qmp: add ExecuteQueryMigration

- CONTRIBUTING.md
This commit clarifies the process to be used when reporting security issues.
> Update guidelines on security issue reporting

- CONTRIBUTING.md
- CONTRIBUTORS.md
- qemu/examples_test.go
- qemu/image.go
- qemu/qemu.go
- qemu/qemu_arch_base.go
- qemu/qemu_arch_base_test.go
- qemu/qemu_test.go
- qemu/qmp.go
- qemu/qmp_test.go
This PR clarifies the template header that is to be used at the beginning of each govmm source file.  It updates all existing source files to adhere to this template and also adds a CONTRIBUTORS.md fie.
> Update file headers , CONTRIBUTING.md and add CONTRIBUTORS.md

- CONTRIBUTORS.md
> Contributors: Add my name

- CONTRIBUTORS.md
Signed-off-by: Clare Chen <clare.chenhui@huawei.com>
> Contributors: Add Clare Chen to CONTRIBUTORS.md

- qemu/qmp.go
- qemu/qmp_test.go
Only get 'QMP command failed' error message now when execute QMP
command by 'executeCommandWithResponse' failed. This patch will
output more error detail.
Signed-off-by: NingBo <ning.bo9@zte.com.cn>
> qmp: Output error detail when execute QMP command failed

- qemu/qmp.go
- qemu/qmp_test.go
In newer versions of QEMU, like 4.0-rc2, QMP events can be thrown even before
the QMP-version response, one example of this behaviour is when a virtio serial
is closed and a VSERPORT_CHANGE event is thrown.
Re-implement mainLoop to check the data received from the VM channel, since
it's not a guarantee that the first data read from the VM channel is the
QMP version.
fixes https://github.com/kata-containers/runtime/issues/1474
> qemu/qmp: re-implement mainLoop

- qemu/qmp.go
- qemu/qmp_test.go
Hotplug virtio-blk with multiqueue support.
> qmp: add virtio-blk multiqueue

- qemu/qemu.go
- qemu/qemu_arch_base.go
- qemu/qemu_test.go
- qemu/qemus390x.go
Dimm is not supported on s390x
Fixes: #106
> s390x: dimm not supported

- qemu/qemu.go
Fixes #124
Signed-off-by: bpradipt@in.ibm.com
> Enable Numa support for Power (ppc64le) architecture

- qemu/qemu.go
support tdx-guest guest objects
cc @sameo 
> qemu: add support for tdx-guest object

- qemu/qemu.go
> qemu: add support for SevGuest object

- qemu/qemu.go
add credentials to the command attribute
Fixes #2444
Signed-off-by: Feng Wang <feng.wang@databricks.com>
Related: https://github.com/kata-containers/kata-containers/pull/2432
> qemu: Add credentials to qemu Cmd

- qemu/qmp.go
ExecuteBlockdevAddWithDriverCache has three one parameter driver
than ExecuteBlockdevAddWithCache.
Parameter driver can set the driver of block device.
Fixes: #198
Signed-off-by: Hui Zhu <teawater@antfin.com>
> QMP: Add ExecuteBlockdevAddWithDriverCache

- qemu/qemu.go
- qemu/qemu_test.go
Define and implement memory-backend-epc object
> qemu: add support for SGX
